# Generated by Django 3.2.4 on 2021-06-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='atualizacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='atualizacao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, default='', verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criacao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='atualizacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='atualizacao'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criacao'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
